/**
 * Videos Database can be added here.
 * You can add videos of your wish with different attributes
 * */
import { v4 as uuid } from "uuid";

export const videos = [
  {
    _id: uuid(),
    url: "https://www.youtube.com/watch?v=1UIhKZCPMYM",
    title: "Basic Badminton for Beginners.",
    thumbnail_url: "https://i.ytimg.com/vi/1UIhKZCPMYM/hqdefault.jpg",
    category: "Beginners",
    likes: "44K",
    views: "50K views",
    added: "25 days ago",
  },
  {
    _id: uuid(),
    url: "https://www.youtube.com/watch?v=SpnjWGBEtoU",
    title:
      "Rules of Badminton EXPLAINED! | SINGLES Badminton Rules | Badminton Training in Hindi",
    thumbnail_url: "https://i.ytimg.com/vi/SpnjWGBEtoU/hqdefault.jpg",
    category: "Beginners",
    likes: "60K",
    views: "80K views",
    added: "2 months ago",
  },
  {
    _id: uuid(),
    url: "https://www.youtube.com/watch?v=jheCYQgupc0",
    title: "How to Smash? | Badminton School Hindi",
    thumbnail_url: "https://i.ytimg.com/vi/jheCYQgupc0/hqdefault.jpg",
    category: "Beginners",
    likes: "1M",
    views: "1.1M views",
    added: "1 year ago",
  },
  {
    _id: uuid(),
    url: "https://www.youtube.com/watch?v=t7pGqYhbJEA",
    title:
      "Mixed Team Bronze - SIN vs IND - WD - 2014 Commonwealth Games badminton",
    thumbnail_url: "https://i.ytimg.com/vi/t7pGqYhbJEA/hqdefault.jpg",
    category: "InterMediate",
    likes: "2K",
    views: "4K views",
    added: "5 months ago",
  },
  {
    _id: uuid(),
    url: "https://www.youtube.com/watch?v=S2-G_tbIj80",
    title: "12 Basic Badminton Techniques that you MUST Know - Introduction",
    thumbnail_url: "https://i.ytimg.com/vi/S2-G_tbIj80/hqdefault.jpg",
    category: "InterMediate",
    likes: "5M",
    views: "5.2M views",
    added: "3 years ago",
  },
  {
    _id: uuid(),
    url: "https://www.youtube.com/watch?v=nP5rWtBm9BQ",
    title: "How To Defend In Doubles - The Fundamentals Of Badminton Defence",
    thumbnail_url: "https://i.ytimg.com/vi/nP5rWtBm9BQ/hqdefault.jpg",
    category: "InterMediate",
    likes: "99K",
    views: "1M views",
    added: "2 years ago",
  },
  {
    _id: uuid(),
    url: "https://www.youtube.com/watch?v=kzWpvuWeih0",
    title:
      "Backhand Serve - A step-by-step guide EVERY BADMINTON PLAYER NEEDS!",
    thumbnail_url: "https://i.ytimg.com/vi/kzWpvuWeih0/hqdefault.jpg",
    category: "InterMediate",
    likes: "20K",
    views: "25K views",
    added: "21 days ago",
  },
  {
    _id: uuid(),
    url: "https://www.youtube.com/watch?v=Hf-n1yfd8II",
    title:
      "Badminton Semi-Finals: Lee Chong Wei vs Lin Dan - Rio 2016 FULL Replay | Throwback Thursday",
    thumbnail_url: "https://i.ytimg.com/vi/Hf-n1yfd8II/hqdefault.jpg",
    category: "Advanced",
    likes: "55k",
    views: "70K views",
    added: "7 month ago",
  },
  {
    _id: uuid(),
    url: "https://www.youtube.com/watch?v=uK3L6H20MTw",
    title: "High beginner to intermediate classes with ST Badminton",
    thumbnail_url: "https://i.ytimg.com/vi/uK3L6H20MTw/hqdefault.jpg",
    category: "Advanced",
    likes: "10K",
    views: "20K views",
    added: "1 months ago",
  },
  {
    _id: uuid(),
    url: "https://www.youtube.com/watch?v=4E3Uqc7HflQ",
    title: "7 Tactical Advice for Single Players",
    thumbnail_url: "https://i.ytimg.com/vi/4E3Uqc7HflQ/hqdefault.jpg",
    category: "Advanced",
    likes: "2M",
    views: "3M views",
    added: "1 year ago",
  },
  {
    _id: uuid(),
    url: "https://www.youtube.com/watch?v=js7yajZq3fQ",
    title: "10 MOST FAMOUS Badminton Trick Shots",
    thumbnail_url: "https://i.ytimg.com/vi/js7yajZq3fQ/hqdefault.jpg",
    category: "Advanced",
    likes: "70K",
    views: "1M views",
    added: "2 months ago",
  },
  {
    _id: uuid(),
    url: "https://www.youtube.com/watch?v=klAbKqpTHpo",
    title:
      "PV Sindhu 🇮🇳 - The First Indian Woman to win an Olympic Silver Medal! | Athlete Highlights",
    thumbnail_url: "https://i.ytimg.com/vi/klAbKqpTHpo/hqdefault.jpg",
    category: "Top Tournaments",
    likes: "5K",
    views: "20K views",
    added: "5 days ago",
  },
  {
    _id: uuid(),
    url: "https://www.youtube.com/watch?v=n20IQaOMLZQ",
    title:
      "Lin Dan Vs. Lee Chong Wei - best rallies and highlights from Asian Championship",
    thumbnail_url: "https://i.ytimg.com/vi/n20IQaOMLZQ/hqdefault.jpg",
    category: "Top Tournaments",
    likes: "49k",
    views: "70K views",
    added: "25 days ago",
  },
  {
    _id: uuid(),
    url: "https://www.youtube.com/watch?v=hkDDMG0edKU",
    title: "Top 10 Net Plays of LEE CHONG WEI",
    thumbnail_url: "https://i.ytimg.com/vi/hkDDMG0edKU/hqdefault.jpg",
    category: "Top Tournaments",
    likes: "34K",
    views: "40K views",
    added: "25 days ago",
  },
  {
    _id: uuid(),
    url: "https://www.youtube.com/watch?v=1xhVH-cUZLo",
    title:
      "Badminton Thug Life | Savage Badminton Rallies | Savage & Thug Badminton Moments | God of Sports",
    thumbnail_url: "https://i.ytimg.com/vi/1xhVH-cUZLo/hqdefault.jpg",
    category: "Top Tournaments",
    likes: "3M",
    views: "4M views",
    added: "3 years ago",
  },
  {
    _id: uuid(),
    url: "https://www.youtube.com/watch?v=JtUgTDRB39M",
    title: "Badminton Respect 2021",
    thumbnail_url: "https://i.ytimg.com/vi/JtUgTDRB39M/hqdefault.jpg",
    category: "Top Tournaments",
    likes: "50K",
    views: "60K views",
    added: "29 days ago",
  },
  {
    _id: uuid(),
    url: "https://www.youtube.com/watch?v=uIj03RsGrJA",
    title: "Men's Badminton 🏸 Gold Medal Match | Tokyo Replays",
    thumbnail_url: "https://i.ytimg.com/vi/uIj03RsGrJA/hqdefault.jpg",
    category: "Top Tournaments",
    likes: "90K",
    views: "1.2M",
    added: "5 months ago",
  },
];
